### ISSUE TITLE
Error in console after upgrade to 7.4.3

### ISSUE THREAD

**Issue by AviadBelulu** [bfwg/ngx-drag-scroll#244]
I have noticed a new issue after upgrading to 7.4.3
using angular 8.1.0
Chrome Version 75.0.3770.100 

The package is working(!) but when starting the page I am getting this issue in the console:

ng:///AppModule/TabsetComponent.ngfactory.js:115 ERROR TypeError: Cannot read property '_elementRef' of undefined
    at DragScrollComponent.push../node_modules/ngx-drag-scroll/fesm5/ngx-drag-scroll.js.DragScrollComponent.adjustMarginToLastChild (vendor.js:394240)
    at DragScrollComponent.push../node_modules/ngx-drag-scroll/fesm5/ngx-drag-scroll.js.DragScrollComponent.ngAfterViewInit (vendor.js:393423)
    at callProviderLifecycles (vendor.js:65733)
    at callElementProvidersLifecycles (vendor.js:65707)
    at callLifecycleHooksChildrenFirst (vendor.js:65697)
    at checkAndUpdateView (vendor.js:73582)
    at callViewAction (vendor.js:73814)
    at execComponentViewsAction (vendor.js:73756)
    at checkAndUpdateView (vendor.js:73579)
    at callViewAction (vendor.js:73814)

In the html I am using it like that:

<drag-scroll #nav class="drag-style" [scrollbar-hidden]="true" [drag-scroll-y-disabled]="true" [drag-scroll-x-disabled]="false" [drag-disabled]="true">

    <li drag-scroll-item....> 
    ....
</drag-scroll>

 In this line I can see an ERROR CONTEXT 
![qq8](https://user-images.githubusercontent.com/42140045/61032656-86b15280-a3ca-11e9-9fa1-6292e96b36ac.png)

Before using this version there was no error (but I used an old one ^_^).

**Comment by bfwg** [comment]
7.4.3 does not fully support Angular 8.0. Can you try the latest release(8.0.0-beta.1)?

**Comment by AviadBelulu** [comment]
> 7.4.3 does not fully support Angular 8.0. Can you try the latest release(8.0.0-beta.1)?

Thank you.
The issue is the exact same (in "ngx-drag-scroll": "^8.0.0-beta.1",)
I hope you will be able to resolve it soon :)
